language: node_js

node_js: "6"

os:
- linux
- osx
matrix:
  fast_finish: true

branches:
  only:
    - master
    - beta

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
